language: C++
dist: bionic

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y cmake ninja-build
  - cmake --version
  - pip install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir build
  - cd build
  - conan install .. --build=missing
  - cmake .. -G Ninja
  - ninja
  - ctest
  - lcov --capture --initial --rc lcov_branch_coverage=1 -d src/ -o initial.info
  - lcov --capture --rc lcov_branch_coverage=1 -d src/ -o coverage.info
  - lcov --rc lcov_branch_coverage=1 --add-tracefile initial.info --add-tracefile coverage.info -o overall.info
  - lcov --list --rc lcov_branch_coverage=1 overall.info
