language: C++
dist: bionic

compiler:
  - gcc

install:
  - sudo apt-get install -y cmake ninja-build
  - pip install conan

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G Ninja
  - ninja
  - ctest

