language: C++
dist: focal

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y cmake ninja-build lcov
  - pip install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan --version
  - cmake --version
  - ninja --version
  - ctest --version
  - lcov --version

script:
  - mkdir build
  - cd build
  - conan install .. --build=missing
  - cmake .. -G Ninja
  - ninja
  - ctest
  - if [ $TRAVIS_COMPILER == "gcc" ]; then
      lcov --config-file ../.lcovrc --capture --initial -d src/ -o initial.info;
      lcov --config-file ../.lcovrc --capture -d src/ -o coverage.info;
      lcov --config-file ../.lcovrc --add-tracefile initial.info --add-tracefile coverage.info -o overall.info;
      lcov --config-file ../.lcovrc --list overall.info;
    fi
