language: C++
dist: bionic

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y cmake ninja-build
  - pip install conan
  - conan profile new default --detect
  - if [ "$TRAVIS_COMPILER" == "gcc" ]; then conan profile update settings.compiler.libcxx=libstdc++11 default; fi

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G Ninja
  - ninja
  - ctest
