language: C++
dist: bionic

compiler:
  - gcc

install:
  - sudo apt-get install -y cmake ninja-build
  - pip install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G Ninja
  - ninja
  - ctest

